package te;

import java.util.ListResourceBundle;

public class Language_ru  extends ListResourceBundle {

	@Override
	protected Object[][] getContents() {
		// TODO Auto-generated method stub
		return contents;
	}
	
	private Object[][] contents = {
            { "ui.menu.data.header"   , "Данные"},
            { "ui.menu.write.header"   , "Запись"},
            { "ui.menu.settings.header"   , "Настройки"},
            { "ui.menu.data.item1"   , "Загрузить"},
            { "ui.menu.data.item2"   , "Сохранить как..."},
            { "ui.menu.data.item3"   , "Сохранить состояние"},
            { "ui.menu.data.item4"   , "Очистить все"},
            { "ui.menu.data.item5"   , "Закрыть"},
            { "ui.menu.write.item1"   , "Писать только в jpg"},
            { "ui.menu.write.item2"   , "Писать только в eps"},
            { "ui.menu.write.item3"   , "Писать и в eps и в jpg"},
            { "ui.menu.write.item4"   , "Записать метаданные в файлы"},
            { "ui.menu.write.item4cancel"   , "Остановить запись метаданных"},
            { "ui.menu.settings.item1"   , "Язык интерфейса: Русский"},
            { "ui.menu.settings.item2"   , "Язык интерфейса: Английский"},
            { "ui.menu.settings.item3"   , "О программе"},
            { "alert.error.title", "Ошибка" },
            { "alert.error.loaderror.header", "Ошибка загрузки" },
            { "alert.error.loaderror.content", "Невозможно загрузить файл" },
            { "alert.error.saveerror.header", "Ошибка сохранения" },
            { "alert.error.saveerror.content", "Невозможно сохранить файл" },
            { "ui.tabs.keyvars.header"   , "Переменные \nключей"},
            { "ui.tabs.descvars.header"   , "Переменные \nописаний"},
            { "ui.tabs.targets.header"   , "Таргеты"},
            { "ui.tabs.foldervars.header"   , "Переменные папок"},
            { "ui.tabs.keys.header"   , "Ключи"},
            { "ui.tabs.descriptions.header"   , "Описания"},
            { "ui.tabs.titles.header"   , "Заголовки"},
            { "log.message.unnalloweddescription"   , "Недопустимые символы в одном из текстовых полей вкладки Описание"},
            { "log.message.unnallowedkeywords"   , "Недопустимые символы в текстовом поле вкладки Заголовок"},
            { "log.message.unnallowedvars"   , "Недопустимые символы в одном значений переменной "},
            { "log.message.unnallowedtarget"   , "Недопустимые символы в одном из полей Таргет"},
            { "log.message.unnallowedtarget1"   , "Недопустимые символы в одном из полей Таргет1"},
            { "log.message.unnallowedtarget2"   , "Недопустимые символы в одном из полей Таргет2"},
            { "alert.error.duplicatevariables", "Имена переменных не должны повторяться, исправьте прежде чем продолжить" },
            { "alert.error.nofolder", "Папка не выбрана или не существует" },
            { "alert.error.nofiles", "В выбранной корневой папке нет папок с файлами " },
            { "alert.error.incorrectdata", "Некорректные входные данные, невозможно осуществить запись. Подробности в файле лога" },
            { "alert.error.writeerror", "ERROR: ошибка записи метаданных в " },
            { "alert.info.done", "ГОТОВО: Метаданные были записаны для файлов: " },
            { "alert.warn.done", "WARNING! Метаданные были записаны для файлов: " },
            { "alert.warn.done2", ", не получилось записать файлов: " },
            { "alert.problem.done", "\nВо время вычисления метаданных были проблемы, смотрите файл лога" },
            { "alert.error.done", "Запись метаданных завершена с ошибкой. Смотрите файл лога" },
            { "alert.write.cancelled", "Запись методанных была отменена" },
            { "alert.info.selectfolder", "Выберите корневую папку (в ней должны быть папки с вашими файлами)" },
            { "alert.conf.clear", "Вы уверены? Все данные в приложении будут удалены" },
            { "alert.conf.clear.title", "Очистка" },
            { "alert.conf.clear.header", "Необходимо подтверждение" },
            { "log.message.write", "Запись метаданных в файл " },
            { "parser.unexistedvar.begin", "Переменная с именем " },
            { "parser.unexistedvar.end", " не существует"},
            { "parser.badsymbols", "В тексте присутствуют специальные символы <>[] вне правильного синтаксиса вставки переменной" },
            { "ui.selector.text", "<текст>"},
            { "ui.tabs.descriptions.maxchars", "Максимальное число символов: "},
            { "alert.error.pastevars", "ERROR: Ошибка вставки переменных в строку: "},
            { "ui.tabs.keys.all", "Все"},
            { "ui.tabs.keys.wordscount", "Слов: "},
            { "ui.tabs.vars.delimiter.space", "ПРОБЕЛ"},
            { "ui.tabs.vars.delimiter.newline", "ПЕРЕНОС СТРОКИ"},
            { "ui.tabs.vars.loadhint", "Загрузить из файла набор данных"},
            { "ui.tabs.vars.savehint", "Сохранить в файл набор данных"},
            { "alert.error.addtoform.content", "Не могу добавить элементы на форму" },
            { "alert.error.removeelements.content", "Не могу удалить элементы" },
            { "alert.load.content", "Выберите файл с данными" },
            { "alert.save.content", "Сохраните данные в файл" },
            { "ui.tabs.desc.random"   , "Рандом"},
            { "ui.tabs.desc.vars"   , "Переменные"},
            { "ui.tabs.desc.desc"   , "Описание"},
            { "ui.tabs.desc.refresh"   , "Обновить"},
            { "ui.tabs.keys.vars"   , "Переменные ключей"},
            { "ui.tabs.keys.count"   , "Число ключей"},
            { "ui.tabs.keys.main"   , "Основной блок"},
            { "ui.tabs.keys.addvar"   , "Добавить Переменную Папки"},
            { "ui.tabs.keys.addtarget"   , "Добавить Таргет"},
            { "ui.tabs.keys.refresh"   , "ОБНОВИТЬ"},
            { "ui.tabs.main.writebtn"   , "Записать метаданные в файлы"},
            { "ui.tabs.main.cancelbtn"   , "Прервать запись"},
            { "ui.tabs.main.clearbtn"   , "Очистить все"},
            { "ui.tabs.main.selectfolder"   , "<Выберите папку с файлами>"},
            { "ui.tabs.targets.save"   , "Сохранить"},
            { "ui.tabs.targets.load"   , "Загрузить"},
            { "ui.tabs.title.takefromdesc"   , "Заголовок берется из описания"},
            { "ui.tabs.varcont.name"   , "Имя переменной"},
            { "ui.tabs.varcont.devider"   , "Разделитель"},
            { "ui.tabs.varcont.values"   , "Значения (через разделитель)"},
            { "ui.tabs.varcont.delete"   , "Удалить"},
            { "ui.tabs.varcont.save"   , "Сохранить"},
            { "ui.tabs.varcont.load"   , "Загрузить"},
            { "log.warn.epsnotfound"   , "Не найден парный eps файл для: "}
    };
}
